### ISSUE TITLE
Encode Mask for ControlNet

### ISSUE THREAD

**Issue by SnowdenLee** [sail-sg/EditAnything#10]
Hi, 
I'm wondering how the masks are encoded as the input of ControlNet. If I understood correctly, the masks predicted by SAM are binary masks without class information. So did you randomly sample colors for each mask or? 

Thanks a lot in advance!

**Comment by gasvn** [comment]
The color is used for visualization only. We use the encoded mask id as the input to the ControlNet.

**Comment by SnowdenLee** [comment]
Thank you!
