### ISSUE TITLE
Train on SD 1.5

### ISSUE THREAD

**Issue by ArcticFaded** [sail-sg/EditAnything#2]
Would it be possible to also release a controlnet model with SD 1.5 as the base model?

**Comment by gasvn** [comment]
I can train one if you need it. Is there a reason for this? Doest SD1.5 has some advantage over SD2.0?

**Comment by ArcticFaded** [comment]
Not really in terms of technical advantage - but when looking through Civit.ai most of the models on that platform are on SD 1.5

**Comment by gasvn** [comment]
okay, then I will train one very soon.

**Comment by gasvn** [comment]
hi, I have trained new sam condition models based on sd15 and sd21. These models are trained with more images and longer iterations. https://github.com/sail-sg/EditAnything#model-zoo
