### ISSUE TITLE
Question: can I apply a partial segmentation control image?

### ISSUE THREAD

**Issue by DJBen** [sail-sg/EditAnything#29]
## Summary

I would like to achieve some masked inpainting, but want to limit the segmentation to only a part of the image, and left regions out of the segmentation mask without constraints. 

## Motivation

The motivation comes from the pains of regular inpainting - if I only supply a mask and a prompt without further constraints, the model will usually add unwanted features to the subject. See below example, the inpainted image grows extra legs on the dog.

Prompt: "dog on the beach, best quality"

| Original image from segment-anything example | Mask | Inpainted image with controlnet-inpaint |
| --- | --- | --- |
| ![Doggo](https://github.com/sail-sg/EditAnything/assets/2078653/df9bfc63-ac69-4625-a5e1-3d1155111b65) | ![mask_image](https://github.com/sail-sg/EditAnything/assets/2078653/7c0c30c1-9b92-49c1-af06-83ac94f398ec) | ![00003-2920368284](https://github.com/sail-sg/EditAnything/assets/2078653/71effd18-a790-4e36-bb73-3a42afb66490) |

To prevent this, I am thinking of using a segment-mask control net to constrain the extent of the primary subject. I use the following script to assign the masked region as segment 1, and other region as segment 0, but it results in the model recognizing everything else uniformly. See produced image.

```python
        def mask_to_control(mask):
            # mask is a binary mask after HWC3(...)
            res = np.zeros((mask.shape[0], mask.shape[1], 3))
            res[:, :, 0] = np.where(mask[:, :, 0] >= 128, 0, 1)
            return res
```

![881af9747e4b4e6f81ee59032770e35e](https://github.com/sail-sg/EditAnything/assets/2078653/6c96c4e9-f975-4e0e-a552-ae9be6d8ad6d)

I would like the image not be bounded by the segmentation mask outside of the masked region, is that possible?
I am still new with controlnet. Please also don't hesitate to point out any mistakes. Glad to hear from all of ya!

**Comment by DJBen** [comment]
@ikuinen thank you for your quick reply! I tried lower mask alignment strength, and it is not very optimal - it sometimes will grow extra legs, while not diversifying the background much.

> Another way is to give pixel-wise control scales instead of a single scalar.

Can you elaborate on this approach? Which parameter should I supply? 🙏

**Comment by ikuinen** [comment]
Thanks for your interest. The mask alignment strength is a control scalar, while I think you could use a heatmap-like control scale. The value in region of dog could be one. The area around the dog could be lower and the rest could be zero. Just a simple idea and haven't tried yet. This may be a further feature that can be added into EditAnything.

**Comment by DJBen** [comment]
@ikuinen Thank you for your insight - I would like to experiment your approach, but I didn't locate a way to provide a heatmap as you described.

In `StableDiffusionControlNetInpaintPipeline`, `__call__`: I think `control_net_conditioning_scale` is a `float` or `List[float]`, and the `alignment_ratio` looks like a `Optional[float]`.

Could you give a code pointer of how this is achieved? Much thanks!

**Comment by DJBen** [comment]
That is amazing. You are awesome. I'll try it at my earliest convenience.
