### ISSUE TITLE
Seems a bug in editany_lora.py

### ISSUE THREAD

**Issue by SkyCol** [sail-sg/EditAnything#50]
the function _get_pipeline_embeds_ will throw an error when the tokens of negtive_prompt greater than prompt.

**Comment by gasvn** [comment]
Thanks for the feedback. This bug should be fixed in the new github version. You can try it now.

**Comment by SkyCol** [comment]
> Thanks for the feedback. This bug should be fixed in the new github version. You can try it now.

It's not useful by the update, because when  count_prompt < count_negative_prompt, the tokenizer of prompt may still > the tokenizer of negative_prompt. However I pulled a request which has solved this problem.
