### ISSUE TITLE
Has the author of this repository given up?

### ISSUE THREAD

**Issue by zongmi** [sail-sg/EditAnything#71]
Has the author of this repository given up?

**Comment by gasvn** [comment]
No, just been a little bit busy recently. Will keep update this repo.  Any pull request are very welcomed.

**Comment by zongmi** [comment]
@gasvn 
have some problem,When do you have time to take a look?
https://huggingface.co/spaces/shgao/EditAnything

**Comment by gasvn** [comment]
The bug is fixed now. Let me know if there are any other issue. Thanks
