### ISSUE TITLE
Model error, cannot find the diffusion_pytorch.bin

### ISSUE THREAD

**Issue by 123-rj** [sail-sg/EditAnything#9]
Executing the sam2edit.py and the two other files keep returning this error:

`OSError: shgao/edit-anything-v0-1-1 does not appear to have a file named diffusion_pytorch_model.bin`

Specifically, the error says:

```
EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64366123-5a1da902152616ed1d113444)

Entry Not Found for url: https://huggingface.co/shgao/edit-anything-v0-1-1/resolve/main/diffusion_pytorch_model.bin.
```
Downloading the .ckpt file from the huggingface also doesn't seem to solve the error. Am I missing something here?

**Comment by gasvn** [comment]
try pip install safetensors

**Comment by 123-rj** [comment]
> try pip install safetensors

Wow, such a simple solution hahaha. Problem solved!

**Comment by gasvn** [comment]
Great!

**Comment by amaigo** [comment]
try huggingface-cli login
